---
- name: Provision Cloud Instance
  hosts: all
  tasks:
    - name: envrnment var is 
      debug:
        var: envrnment

    - name: create real AWS instance
      ec2:
       key_name: dzuev-key
       instance_type: t2.micro
       image: ami-c998b6b2
       instance_tags:
         name: "{{inst_name}}"
       wait: yes
       group: launch-wizard-33
       exact_count: 1
       count_tag: foo
       vpc_subnet_id: subnet-c86b14e2
       assign_public_ip: yes
      when: envrnment == "AWS"
      failed_when: IPMI_IP is defined

    - name: provisioning AWS Instance
      debug:
        msg: "Provisioning Instance in AWS"
      when: envrnment == "AWS"
      failed_when: IPMI_IP is defined

    - name: provisioning GCE Instance
      debug:
        msg: "Provisioning Instance in GCE"
      when: envrnment == "GCE"
      failed_when: IPMI_IP is defined

    - name: provisioning AWS Instance
      debug:
        msg: "Provisioning Instance in MS Azure"
      when: envrnment == "MS Azure"
      failed_when: IPMI_IP is defined

