- hosts: ec2-52-23-122-222.compute-1.amazonaws.com
#- hosts: localhost
#  connection: local
  tasks: 
  - name: login to tf and create instance from there
    shell: /home/ec2-user/terraform apply -auto-approve
    args:
     chdir: /home/ec2-user

  - name: 
    shell: cat /home/ec2-user/terraform.tfstate
    args:
     chdir: /home/ec2-user
    register: tf_vm

  - name: debug on instances
    debug:
      var: tf_vm.results


  - name: Include all .json and .jsn files in vars/all and all nested directories (2.3)
    include_vars:
      dir: '/home/ec2-user'
      files_matching: 'terraform.tfstate'
      name: tf_vm_vars
      extensions:
#        - json
#        - jsn
        - tfstate

  - name: debug on instances
    debug:
      var: tf_vm_vars.results

