- hosts: ec2-52-23-122-222.compute-1.amazonaws.com
  tasks: 
  - name: create template for terraforms
    template: 
     src: main.tf.j2
     dest: /home/ec2-user/main.tf
     owner: ec2-user
     group: ec2-user
     mode: 0755

  - name: login to tf and create instance from there
    shell: /home/ec2-user/terraform apply -auto-approve
    args:
     chdir: /home/ec2-user

  - name: read json file and register
    shell: cat /home/ec2-user/terraform.tfstate
    args:
     chdir: /home/ec2-user
    register: tf_vm

  - set_fact:
      ec2_output: "{{ tf_vm.stdout|from_json }}"

  - name: debug on json
    debug:
      var: ec2_output

