- hosts: ec2-52-23-122-222.compute-1.amazonaws.com
  gather_facts: false
  tasks: 
  - name: read json file and register
    shell: cat /home/ec2-user/terraform.tfstate
    args:
     chdir: /home/ec2-user
    register: tf_vm

  - set_fact:
      ec2_output: "{{ tf_vm.stdout|from_json }}"

  - set_fact:
      vm_dns: "{{ ec2_output.modules[0].resources['aws_instance.web4'].primary.attributes.public_dns }}"

  - name: debug on json.primary
    debug:
      var: ec2_output

  - name: debug on json.public_dns
    debug:
#      var: ec2_output.modules.resources.aws_instance.web4.primary.attributes.public_dns
      var: ec2_output.modules[0].resources['aws_instance.web4'].primary.attributes.public_dns
      var: vm_dns
#      msg: '{{ec2_output.modules}}'

- hosts: "{{ vm_dns }}"
  gather_facts: false
  tasks:
  - file:
      path: /tmp/script.sh
      state: touch
      mode: 0755

